image: docker:latest

stages:
  - build
  - deploy
  

variables:
  DOCKER_IMAGE: kitinat
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # Để tắt TLS cho Docker-in-Docker

services:
  - docker:dind

before_script:
  - apk update
  - apk add --no-cache expect
  - which docker
  - docker info  # Kiểm tra thông tin Docker
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker tag $DOCKER_IMAGE:latest $DOCKER_USERNAME/$DOCKER_IMAGE:latest
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
  artifacts:
    paths:
      - docker-compose.yml
  only:
    - master
# deploy:
#   stage: deploy
#   script:
#   - >
#       expect -f ssh_deploy.exp "$PASS_SETUP"
#     # - >
#     #   sshpass -p "$PASS_SETUP" ssh -o StrictHostKeyChecking=no root@112.213.88.123 '
#     #   cd cafe/ &&
#     #   docker-compose pull &&
#     #   docker-compose down &&
#     #   docker-compose up -d &&
#     #   docker system prune -a -f'
#   dependencies:
#     - build
#   only:
#     - master  # Chỉ deploy khi push code lên nhánh `master`

